### PR TITLE
perf: Text fixes

### PR DESCRIPTION
**Pull request by FabioLuporini**
We will have 2 physical cores at our disposal, not 4...

### CODE REVIEW

**Comment by mlange05** [comment]
Aren't the VM images going to be replicated on 16 core instances?

**Comment by FabioLuporini** [comment]
Yes, but I'm assuming that my display will be projected somewhere, so the attendees will see that we have 2 cores, and 2 cores will be used. The idea was to explicitly tell them to replace 2 with whatever they see, and if they can't get it right, we'll fix it. Also because we don't know whether those are 16 cores on a single socket, or 8+8, or whatever...

**Comment by mlange05** [comment]
I thought we were going to sit on the same 16-core nodes? But maybe not, mhhh... :thinking: 

In any case, this is fine, as long as you explain in the talk what to do.

**Comment by mlange05** [comment]
Ok, then. Merging...

**Pull request merged**
